# Generated by Django 5.2.5 on 2025-08-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
