# Generated by Django 6.1 on 2026-08-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda', '0003_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        # 'bathrooms' and 'bedrooms' were already present on the
        # magda_property table (added out-of-band before migrations were
        # kept in sync). Update Django's migration *state* to match the
        # model without re-running the (already-applied) database changes.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='property',
                    name='bathrooms',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='property',
                    name='bedrooms',
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
            database_operations=[],
        ),
    ]
