# Generated by Django 5.2.3 on 2025-09-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda', '0003_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
