# Generated by Django 6.1 on 2026-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda', '0004_lead_created_at_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('coming_soon', 'Brevemente'), ('reserved', 'Reservado')], default='available', max_length=20),
        ),
    ]
