# Generated by Django 6.1 on 2026-09-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda', '0005_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
