# Generated by Django 6.1 on 2026-09-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda', '0007_property_coordinates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
