# Generated by Django 6.1 on 2026-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda', '0010_lead_phone_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('rent', 'Arrendamento')], default='sale', max_length=10),
        ),
    ]
