# Generated by Django 6.1 on 2026-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magda', '0011_property_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('housing', 'Habitacional'), ('commercial', 'Comercial/Serviços'), ('land', 'Terreno')], default='housing', max_length=12),
        ),
    ]
